# Generated by Django 5.1.6 on 2025-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='church_finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithes', models.IntegerField(max_length=100)),
                ('offerings', models.IntegerField(max_length=100)),
                ('seeds', models.IntegerField(max_length=100)),
            ],
        ),
    ]
