# Generated by Django 5.1.6 on 2025-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church_finance',
            name='offerings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='church_finance',
            name='seeds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='church_finance',
            name='tithes',
            field=models.IntegerField(),
        ),
    ]
