# Generated by Django 5.1.6 on 2025-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0002_alter_church_finance_offerings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('seed', 'Seed')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='church_finance',
        ),
    ]
