# Generated by Django 5.1.6 on 2025-03-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0004_churchmember_churchprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchProjects',
            new_name='ChurchProject',
        ),
        migrations.RenameModel(
            old_name='Financial_Transactions',
            new_name='Financial_Transaction',
        ),
    ]
