# Generated by Django 5.1.6 on 2025-03-10 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0006_rename_name_churchmember_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='fellowship',
            field=models.CharField(choices=[('children', 'Children Ministry'), ('junior_youth', 'Junior Youth'), ('youth', 'Youth Fellowship'), ('women', "Women's Fellowship"), ('men', "Men's Fellowship"), ('gospel', 'Gospel Band')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
