# Generated by Django 5.1.6 on 2025-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0007_churchmember_fellowship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchproject',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
